env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  no-console: off
  linebreak-style: 0
  react/react-in-jsx-scope: off
  jsx-a11y/tabindex-no-positive: off
  jsx-a11y/anchor-has-content: off
  jsx-a11y/anchor-is-valid: off
  react/function-component-definition: off
  import/prefer-default-export: off
  react/prop-types: off
  no-underscore-dangle: off
  max-len: ["error", {
    "code": 120,
    "ignoreComments": true,
    "ignoreTrailingComments": true,
    "ignoreUrls": true,
    "ignoreStrings": true,
    "ignoreTemplateLiterals": true
  }]
  # no-console: ["error", { allow: ["error"] }]
